// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
require('chromedriver');
describe('addnewdisease', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('addnewdisease', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1850, 1053)
    await driver.findElement(By.id("inputEmail")).sendKeys("admin")
    await driver.findElement(By.id("inputPassword")).sendKeys("admin")
    await driver.findElement(By.css(".btn")).click()
  /*   await driver.findElement(By.css("#patients-waiting_wrapper .dataTables_scrollHead")).click()
    {
      const element = await driver.findElement(By.css("#patients-waiting_wrapper .dataTables_scrollHead"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    } */
    await driver.findElement(By.xpath("/html/body/div[1]/nav/div[2]/div/ul/li[3]/a")).click()
    await driver.findElement(By.name("diseaseName")).click()
    await driver.findElement(By.name("diseaseName")).sendKeys("cancer")
    await driver.findElement(By.name("diseaseScore")).sendKeys("50")
    await driver.findElement(By.name("Submit")).click()
  })
})
