// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
require('chromedriver');
describe('Add_Doctor', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Add_Doctor', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1850, 1053)
    await driver.findElement(By.id("inputEmail")).sendKeys("admin")
    await driver.findElement(By.id("inputPassword")).sendKeys("admin")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Add patient")).click()
    await driver.findElement(By.id("first-name")).click()
    await driver.findElement(By.id("first-name")).sendKeys("Mark")
    await driver.findElement(By.name("lastName")).sendKeys("young")
    await driver.findElement(By.name("hospitalNumber")).sendKeys("142")
    await driver.findElement(By.name("dateOfBirth")).sendKeys("21/02/1995")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    await driver.findElement(By.name("PD[]")).click()
    await driver.findElement(By.css(".even input")).click()
    await driver.findElement(By.css(".odd:nth-child(3) > td:nth-child(3)")).click()
    await driver.findElement(By.css(".odd:nth-child(3) > td:nth-child(3)")).click()
    await driver.findElement(By.css(".odd:nth-child(3) > td:nth-child(3)")).click()
    await driver.findElement(By.css(".even input")).click()
    await driver.findElement(By.name("Submit")).click()
  })
})
