// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Add_Doctor', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:3000/').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Add_Doctor', async function() {
    // Test name: Add_Doctor
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/ | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1850x1053 | 
    await driver.manage().window().setRect(1850, 1053)
    // 3 | type | id=inputEmail | admin
    await driver.findElement(By.id("inputEmail")).sendKeys("admin")
    // 4 | type | id=inputPassword | admin
    await driver.findElement(By.id("inputPassword")).sendKeys("admin")
    // 5 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | linkText=Add patient | 
    await driver.findElement(By.linkText("Add patient")).click()
    // 7 | click | id=first-name | 
    await driver.findElement(By.id("first-name")).click()
    // 8 | type | id=first-name | Mark
    await driver.findElement(By.id("first-name")).sendKeys("Mark")
    // 9 | type | name=lastName | young
    await driver.findElement(By.name("lastName")).sendKeys("young")
    // 10 | type | name=hospitalNumber | 142
    await driver.findElement(By.name("hospitalNumber")).sendKeys("142")
    // 11 | type | name=dateOfBirth | 21/02/1995
    await driver.findElement(By.name("dateOfBirth")).sendKeys("21/02/1995")
    // 12 | click | css=.btn-primary:nth-child(1) | 
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // 13 | click | name=PD[] | 
    await driver.findElement(By.name("PD[]")).click()
    // 14 | click | css=.even input | 
    await driver.findElement(By.css(".even input")).click()
    // 15 | click | css=.odd:nth-child(3) > td:nth-child(3) | 
    await driver.findElement(By.css(".odd:nth-child(3) > td:nth-child(3)")).click()
    // 16 | click | css=.odd:nth-child(3) > td:nth-child(3) | 
    await driver.findElement(By.css(".odd:nth-child(3) > td:nth-child(3)")).click()
    // 17 | click | css=.odd:nth-child(3) > td:nth-child(3) | 
    await driver.findElement(By.css(".odd:nth-child(3) > td:nth-child(3)")).click()
    // 18 | click | css=.even input | 
    await driver.findElement(By.css(".even input")).click()
    // 19 | click | name=Submit | 
    await driver.findElement(By.name("Submit")).click()
  })
})
